# Generated by Django 3.1.4 on 2021-01-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageproject',
            name='estimate_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
