# Generated by Django 3.1.4 on 2021-01-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Management', '0002_auto_20210106_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageproject',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manageproject',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
