# Generated by Django 3.1.4 on 2021-01-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Management', '0005_auto_20210108_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='project_file',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='projectfile'),
        ),
    ]
